### ISSUE TITLE
The packs directory should contain ONLY the entry files

### ISSUE THREAD

**Issue by mattgrande** [gbarillot/rails-vue-demo-app#6]
Hi there,

First of all, thanks for this. It got me up & running in a Rails/Vue/Vuex environment very quickly, and has served as a great structure.

However, I came across an issue. The packs directory should _only_ contain the entry files (ie, `application.js` and `admin/application.js`), and all other files should be external to that.

See here: https://github.com/rails/webpacker/issues/1284#issuecomment-415099505

If everything is within `packs`, everything is considered to be an entry file, which means you get out of memory errors as your application grows.

See also: https://github.com/rails/webpacker#usage

Note the line: `# only webpack entry files here`

**Comment by gbarillot** [comment]
Wow ! This is really helpful. I must say I'm quite surprised because we actually use this same idea/structure in a huge Vue app at work and never had any problem (ok, so far...). Correct me if I'm wrong, but from what I can recall this is also how a raw, empty, Rails app looks like, with the hello.vue component right inside of the /packs directory, isn't it? I'm surprised this could lead to such problems in the long run. 

Ok, I'm going to dig a bit deeper about this potential issue (some questions about Webpack versions and config., to be precise) but will probably refactor and relink things soon... If you have time for a PR on your side, you're welcome ;-)

Thank you.

**Comment by mattgrande** [comment]
> Correct me if I'm wrong, but from what I can recall this is also how a raw, empty, Rails app looks like, with the hello.vue component right inside of the /packs directory, isn't it?

Unfortunately, I don't know the answer to that.

It's strange, I don't know if it's a widespread issue, or some combination of things or what, but yeah, moving all of my components to a sibling directory sped things up massively for me, and I haven't hit an out-of-memory exception in hours which, a few days ago, wouldn't've happened.

**Comment by gbarillot** [comment]
Mmmh... weird. I just tried a massive refactor + relink in the app we have at work in order to have a significant amount of JS code. Result: absolutely no difference, time to compile is the same in dev, as well as production Environnements. The output bundle is also the same size in both cases.

I suspect the issue is mostly due to some circular linking (import), no idea where and how precisely this could happen (I never saw it in the wild).   

Anyway, since it is clearly stated here [https://github.com/rails/webpacker#usage](https://github.com/rails/webpacker#usage), as you pointed out, I'm going to re-dispatch + relink the code in /javascripts/packs.

Thank you very much.

**Comment by mattgrande** [comment]
Thanks @gbarillot. Would you like me to make a PR for this repo?

**Comment by gbarillot** [comment]
That would be Aaaaaawesome :-)

**Comment by gbarillot** [comment]
Thank you @mattgrande for the PR!

**Comment by mattgrande** [comment]
No problem! Thanks for the great app.
